### ISSUE TITLE
Possibly bug in case of all channels are busy - unit test needed

### ISSUE THREAD

**Issue by astec** [dgrr/GoSlaves#2]
I have concenrs regards [slavepool.go#L58](https://github.com/themester/GoSlaves/blob/639ecdd00a01f1a2d5c857ca8fa2d9b49492d399/slavepool.go#L58)

I maybe got it wrong but it seems if all channels are busy a task is getting discarded/lost.

You can test it by creating a pool with a worker that sleeps for a seconds and then submitting more tasks then `n` and then checking all tasks have been handled (_counter_).

**Comment by themester** [comment]
Thanks for your issue.

If a channel is busy all runtime stops until channel were available. At this implementation when you call Serve the runtime stops if all slaves are busy. Even so I implemented a test https://github.com/themester/GoSlaves/blob/master/slavepool_test.go#L38

**Comment by astec** [comment]
Still not convinced.

Your unit test will not test properly on my machine that have 16 virtual cores. You should submit at least 1 task more then ‘n’.

If the Serve thread will locked why you have default section at all? If I recall it right you fall through there I’d channel is busy. So yu would iterate over all busy channel and just exit Serve loosing task.

**Comment by themester** [comment]
Okay. See https://github.com/themester/GoSlaves/commit/5afcbe8becb59ef525866710283d492e9c63cdb3 I will wait your feedback.
